"""
• P4.27 A simple random generator is obtained by the formula
rnew = (a · rold + b)%m
and then setting rold to rnew.
Write a program that asks the user to enter an initial value forrold. (Such a value is 
often called a seed). Then print the first 100 random integers generated by this 
formula, using a = 32310901, b = 1729, and m = 224.
"""
import random
import math


def main():
    a = 32310901
    b = 1729
    m = 2 ** 24
    rold = int(input("Please enter your initial value: "))

    for i in range(100):
        rnew = (a * rold + b) % m

        print(f"{i + 1}. Random integer generated: {rnew}")
        rold = rnew


if __name__ == "__main__":
    main()
